# 学习Numpy

In [2]:
import numpy as np

In [2]:
# 列表传入数组
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])
a + b

array([3, 5, 7, 9])

In [3]:
# 全0数组
zero = np.zeros(5)
zero

array([0., 0., 0., 0., 0.])

In [4]:
# 全1数组
one = np.ones(5)
one

array([1., 1., 1., 1., 1.])

In [5]:
# 全1数组
one = np.ones(5, dtype='int')
one

array([1, 1, 1, 1, 1])

In [6]:
# 全1数组
one = np.ones(5, dtype='bool')
one

array([ True,  True,  True,  True,  True])

In [8]:
# 使用fill方法将数组设为指定值
a = np.array([1, 2, 3, 4])
a.fill(5)
a

array([5, 5, 5, 5])

In [10]:
a.fill(2.5) # 原数组是int型的
a

array([2, 2, 2, 2])

In [19]:
a = np.array([1, 2, 3, 4]) # 有bug
a.astype('float')
a.fill(2.5)
a

array([2, 2, 2, 2])

In [20]:
# 生成整数序列
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# 生成整数序列
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

In [23]:
# 生成等差数列
a = np.linspace(1, 10, 20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [24]:
# 生成随机数
a = np.random.rand(10)
a

array([0.33785966, 0.04217829, 0.234158  , 0.54192967, 0.54317065,
       0.52574929, 0.9656443 , 0.40194664, 0.99470611, 0.2805693 ])

In [25]:
# 生成随机数
a = np.random.randn(10) # randn 服从标准正态分布
a

array([-1.3524864 ,  0.19352957, -0.55993437,  0.39206503,  0.21037572,
       -0.41415429, -1.01116545, -1.76226565,  0.30002417,  0.14098456])

In [26]:
a = np.random.randint(1, 10, 10)
a

array([3, 4, 8, 7, 8, 6, 9, 2, 6, 4])

In [28]:
# 查看类型，数组中的数据类型，形状，元素数目，数组维度
print(type(a), a.dtype, a.shape, a.size, a.ndim)

<class 'numpy.ndarray'> int32 (10,) 10 1


In [29]:
# 利用切片求电影每日票房
ob = np.array([21000, 21800, 22240, 23450, 25000])
ob2 = ob[1:] - ob[:-1]
ob2

array([ 800,  440, 1210, 1550])

In [3]:
# 多维数组
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
# 第2行
a[1]

array([5, 6, 7, 8])

In [5]:
# 第2列
a[:,1]

array([2, 6])

In [6]:
# 多维数组
b = np.array([[0,1,2,3,4,5],
              [10,11,12,13,14,15],
              [20,21,22,23,24,25],
              [30,31,32,33,34,35],
              [40,41,42,43,44,45],
              [50,51,52,53,54,55]])
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [7]:
b[0,3:5] # 第一行的第四和第五两个元素

array([3, 4])

In [8]:
b[-2:,-2:] # 最后2行的最后2列

array([[44, 45],
       [54, 55]])

In [9]:
b[:,2] # 第3列

array([ 2, 12, 22, 32, 42, 52])

In [10]:
b[2::2,::2] # 取出3，5行的奇数列

array([[20, 22, 24],
       [40, 42, 44]])

In [11]:
b[(0,1,2,3,4),(1,2,3,4,5)] # 主对角线上的一条次对角线

array([ 1, 12, 23, 34, 45])

In [13]:
# where语句
a = np.array([0,12,5,20])

In [14]:
a > 10

array([False,  True, False,  True])

In [15]:
np.where(a > 10)

(array([1, 3], dtype=int64),)

In [16]:
a[a > 10]

array([12, 20])

In [17]:
a[np.where(a > 10)]

array([12, 20])

In [18]:
# 多维数组操作
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [19]:
a.shape = 2,3
a

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
a = np.arange(6)
a.reshape(2, 3) # reshape不会改变原数组，返回一个新的数组

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
a

array([0, 1, 2, 3, 4, 5])

In [25]:
# 转置
a.shape = 2,3
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [27]:
a.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
# 数组连接

In [32]:
x = np.array([[0,1,2],[10,11,12]])
y = np.array([[50,51,52],[60,61,62]])
z = np.concatenate((x,y),axis=0) # 第一维拼接
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [31]:
z = np.concatenate((x,y),axis=1) # 第二维拼接
z

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [33]:
# 连接成三维数组
z = np.array((x,y))
z

array([[[ 0,  1,  2],
        [10, 11, 12]],

       [[50, 51, 52],
        [60, 61, 62]]])

In [34]:
z = np.vstack((x,y))
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [35]:
z = np.hstack((x,y))
z

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [36]:
z = np.dstack((x,y))
z

array([[[ 0, 50],
        [ 1, 51],
        [ 2, 52]],

       [[10, 60],
        [11, 61],
        [12, 62]]])